spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springboot
  application:
    name: user-service

mybatis:
  type-aliases-package: com.itheima.user_service.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: ${port:8081}

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

